export const C = {
  bg: "#151210",
  panel: "#201C17",
  panelUp: "#2A2520",
  line: "#332D25",
  gold: "#D8A63F",
  goldDim: "#8A6F2E",
  cream: "#F5EDDB",
  muted: "#9C907A",
  ink: "#1C1712",
  red: "#E06A5A",
};

export const CATS = ["Pies", "Sandwiches", "Rolls & Buns", "Sweets", "Hot Food", "Drinks"];

export const DEFAULT_MENU = [
  { id: "p01", name: "Steak Pie", price: 7.9, cat: "Pies" },
  { id: "p02", name: "Steak & Cheese", price: 7.9, cat: "Pies" },
  { id: "p03", name: "Steak & Pepper", price: 7.9, cat: "Pies" },
  { id: "p04", name: "Steak Mushroom", price: 7.9, cat: "Pies" },
  { id: "p05", name: "Steak Bacon Cheese", price: 7.9, cat: "Pies" },
  { id: "p06", name: "Steak Cheese Jalapeño", price: 7.9, cat: "Pies" },
  { id: "p07", name: "Steak Double Cheese", price: 8.7, cat: "Pies" },
  { id: "p08", name: "Mince & Cheese", price: 7.9, cat: "Pies" },
  { id: "p09", name: "Mince Double Cheese", price: 8.7, cat: "Pies" },
  { id: "p10", name: "Mince & Pepper", price: 7.9, cat: "Pies" },
  { id: "p11", name: "Chicken Mushroom", price: 7.9, cat: "Pies" },
  { id: "p12", name: "Chicken & Cheese", price: 7.9, cat: "Pies" },
  { id: "p13", name: "Butter Chicken", price: 7.9, cat: "Pies" },
  { id: "p14", name: "Bacon & Egg Pie", price: 7.9, cat: "Pies" },
  { id: "p15", name: "Double Happy", price: 8.5, cat: "Pies" },
  { id: "p16", name: "Small Mince Pie", price: 3.8, cat: "Pies" },
  { id: "p17", name: "Small Mince Potato", price: 3.8, cat: "Pies" },
  { id: "p18", name: "Sausage Roll", price: 6.0, cat: "Pies" },
  { id: "s01", name: "Mixed Sandwiches", price: 6.3, cat: "Sandwiches" },
  { id: "s02", name: "Egg & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s03", name: "Bacon & Egg Sandwich", price: 7.0, cat: "Sandwiches" },
  { id: "s04", name: "Ham & Cheese", price: 7.0, cat: "Sandwiches" },
  { id: "s05", name: "Ham Cheese & Tomato", price: 7.0, cat: "Sandwiches" },
  { id: "s06", name: "Ham Cheese & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s07", name: "Chicken & Mayo", price: 7.0, cat: "Sandwiches" },
  { id: "s08", name: "Chicken & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s09", name: "Beef Sweet Fruit Chutney", price: 7.0, cat: "Sandwiches" },
  { id: "s10", name: "Chicken & Avocado", price: 7.5, cat: "Sandwiches" },
  { id: "s12", name: "Egg & Mayo", price: 7.0, cat: "Sandwiches" },
  { id: "s13", name: "Ham & Egg", price: 7.0, cat: "Sandwiches" },
  { id: "s14", name: "Egg & Curry", price: 7.0, cat: "Sandwiches" },
  { id: "s15", name: "Egg Curry & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s16", name: "Chicken Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s17", name: "Ham Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s18", name: "Beef Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s19", name: "Salami Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s11", name: "Fruit Salad", price: 6.5, cat: "Sandwiches" },
  { id: "r01", name: "Chicken Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r02", name: "Salami Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r03", name: "Bacon Lettuce Tomato Avocado", price: 7.9, cat: "Rolls & Buns" },
  { id: "r04", name: "Chicken Avocado Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r05", name: "Seafood Roll", price: 8.5, cat: "Rolls & Buns" },
  { id: "r06", name: "Bacon & Egg Bun", price: 7.9, cat: "Rolls & Buns" },
  { id: "r07", name: "Ham Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r08", name: "Beef Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r09", name: "Chicken Camembert Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r10", name: "Chicken Cranberry & Cheese Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "d01", name: "Fresh Cream Donut", price: 4.9, cat: "Sweets" },
  { id: "d02", name: "Fresh Cream Chocolate Donut", price: 4.9, cat: "Sweets" },
  { id: "d03", name: "Fresh Cream Apple Donut", price: 4.9, cat: "Sweets" },
  { id: "d04", name: "Fresh Cream Nutella Donut", price: 4.9, cat: "Sweets" },
  { id: "d05", name: "Chocolate & Nutella Donut", price: 4.0, cat: "Sweets" },
  { id: "d06", name: "Apple Turnover", price: 4.7, cat: "Sweets" },
  { id: "d07", name: "Cream Apple Turnover", price: 5.5, cat: "Sweets" },
  { id: "d08", name: "Lamington", price: 4.9, cat: "Sweets" },
  { id: "d09", name: "Fresh Cream Lamington", price: 5.5, cat: "Sweets" },
  { id: "d10", name: "Choc Caramel Tim Tam Slice", price: 4.9, cat: "Sweets" },
  { id: "d11", name: "Caramel Slice", price: 4.9, cat: "Sweets" },
  { id: "d12", name: "Caramel Fudge Slice", price: 4.9, cat: "Sweets" },
  { id: "d13", name: "Caramel Oreo Slice", price: 4.9, cat: "Sweets" },
  { id: "d14", name: "Caramel Coconut Slice", price: 4.9, cat: "Sweets" },
  { id: "d15", name: "Ginger Slice", price: 4.9, cat: "Sweets" },
  { id: "d16", name: "Lemon Slice", price: 4.9, cat: "Sweets" },
  { id: "d17", name: "Lolly Slice", price: 4.9, cat: "Sweets" },
  { id: "d18", name: "Rocky Road", price: 4.9, cat: "Sweets" },
  { id: "d19", name: "White Chocolate Mars Slice", price: 4.9, cat: "Sweets" },
  { id: "d20", name: "Cookie & Cream Slice", price: 4.7, cat: "Sweets" },
  { id: "d21", name: "Chocolate Brownie", price: 4.9, cat: "Sweets" },
  { id: "d22", name: "Raspberry Cheesecake", price: 5.5, cat: "Sweets" },
  { id: "d23", name: "Carrot Cake", price: 5.0, cat: "Sweets" },
  { id: "d24", name: "Banana Cake", price: 5.0, cat: "Sweets" },
  { id: "d25", name: "Custard Tart", price: 4.5, cat: "Sweets" },
  { id: "d26", name: "Neenish Tart", price: 3.5, cat: "Sweets" },
  { id: "d27", name: "Yoyo", price: 3.5, cat: "Sweets" },
  { id: "d28", name: "Jam Tart", price: 3.0, cat: "Sweets" },
  { id: "d29", name: "Lemon Tart", price: 3.0, cat: "Sweets" },
  { id: "d30", name: "Gingerbread Man", price: 4.9, cat: "Sweets" },
  { id: "d31", name: "Happy Face Cookie", price: 4.9, cat: "Sweets" },
  { id: "d32", name: "Marshmallow Stick", price: 4.5, cat: "Sweets" },
  { id: "d33", name: "Choc Mud / Lemon Sorbet Log", price: 3.5, cat: "Sweets" },
  { id: "h01", name: "Corn Dog", price: 3.0, cat: "Hot Food" },
  { id: "h02", name: "Potato Cake", price: 1.4, cat: "Hot Food" },
  { id: "h03", name: "Hash Brown", price: 0, cat: "Hot Food" },
  { id: "h04", name: "Home Made Dim Sim", price: 2.9, cat: "Hot Food" },
  { id: "h11", name: "Small Dim Sim", price: 1.4, cat: "Hot Food" },
  { id: "h05", name: "Spring Roll", price: 3.5, cat: "Hot Food" },
  { id: "h06", name: "Chicken Wings", price: 2.5, cat: "Hot Food" },
  { id: "h12", name: "Chicken Sweet Chilli Tender", price: 2.5, cat: "Hot Food" },
  { id: "h13", name: "Seafood Stick", price: 2.0, cat: "Hot Food" },
  { id: "h07", name: "Butter Hot Dog", price: 3.7, cat: "Hot Food" },
  { id: "h08", name: "Kransky Sausage", price: 6.0, cat: "Hot Food" },
  { id: "h14", name: "Lasagna Topper", price: 3.9, cat: "Hot Food" },
  { id: "h10", name: "Hot Chips", price: 4.5, cat: "Hot Food" },
  { id: "h09", name: "Bacon Fritter", price: 0, cat: "Hot Food" },
  { id: "h15", name: "Bacon & Egg Toasted", price: 8.0, cat: "Hot Food" },
  { id: "h16", name: "Bacon & Cheese Toasted", price: 8.5, cat: "Hot Food" },
  { id: "h17", name: "Bacon & Egg Roll (Hot)", price: 9.0, cat: "Hot Food" },
  { id: "h18", name: "Bacon & Cheese Roll (Hot)", price: 9.5, cat: "Hot Food" },
  { id: "k01", name: "Soft Drink Can", price: 0, cat: "Drinks" },
  { id: "k02", name: "L&P Can", price: 0, cat: "Drinks" },
  { id: "k03", name: "Soft Drink Bottle 600ml", price: 0, cat: "Drinks" },
  { id: "k04", name: "Water Bottle", price: 0, cat: "Drinks" },
  { id: "k05", name: "Coffee", price: 0, cat: "Drinks" },
  { id: "k06", name: "Flavoured Milk", price: 0, cat: "Drinks" },
];

export const I = {
  pastry: "#E8B95B", crust: "#C08A3E", dark: "#7A5222", biscuit: "#E4C98C",
  cream: "#FFF3DC", white: "#FBF6EA", choc: "#4A2F1D", milk: "#6E4526",
  caramel: "#C97F35", pink: "#F09CB4", red: "#D8483A", jam: "#B83A34",
  yellow: "#F2CE4B", green: "#7FA85A", avo: "#A9C070", bread: "#F3DCA8",
  meat: "#6B3A20", chick: "#F5E6C8", ham: "#F1A9B8", grey: "#B9AE99",
};

export const ICONS = {
  p01: ["pie", I.meat], p02: ["pie", I.yellow], p03: ["pie", "#3A3A3A"],
  p04: ["pie", "#C9B49A"], p05: ["pie", I.red], p06: ["pie", I.green],
  p07: ["pie", I.yellow], p08: ["pie", "#8A4A2A"], p09: ["pie", I.yellow],
  p10: ["pie", "#3A3A3A"], p11: ["pie", "#C9B49A"], p12: ["pie", I.chick],
  p13: ["pie", "#E0862F"], p14: ["pie", I.yellow], p15: ["pie", I.caramel],
  p16: ["pieSmall", "#8A4A2A"], p17: ["pieSmall", I.cream], p18: ["sroll"],
  s01: ["sandwich", I.ham, I.yellow], s02: ["sandwich", I.yellow, I.green],
  s03: ["sandwich", I.red, I.yellow], s04: ["sandwich", I.ham, I.yellow],
  s05: ["sandwich", I.ham, I.red], s06: ["sandwich", I.ham, I.green],
  s07: ["sandwich", I.chick, I.cream], s08: ["sandwich", I.chick, I.green],
  s09: ["sandwich", I.meat, I.caramel], s10: ["sandwich", I.chick, I.avo],
  s11: ["fruitcup"],
  s12: ["sandwich", I.yellow, I.cream], s13: ["sandwich", I.ham, I.yellow],
  s14: ["sandwich", "#E0A93E", I.yellow], s15: ["sandwich", "#E0A93E", I.green],
  s16: ["sandwich", I.chick, I.green], s17: ["sandwich", I.ham, I.green],
  s18: ["sandwich", I.meat, I.green], s19: ["sandwich", "#A33B3B", I.green],
  r01: ["roll", I.green, I.red], r02: ["roll", "#A33B3B", I.green],
  r07: ["roll", I.ham, I.green], r08: ["roll", I.meat, I.red],
  r09: ["roll", I.chick, I.cream], r10: ["roll", I.chick, "#A33B3B"],
  r03: ["roll", I.red, I.avo], r04: ["roll", I.chick, I.avo],
  r05: ["roll", I.ham, I.green], r06: ["roll", I.yellow, I.red],
  d01: ["donut", I.jam, null], d02: ["donut", I.jam, I.choc],
  d03: ["donut", "#B9CF7E", null], d04: ["donut", I.milk, null],
  d05: ["ringdonut"], d06: ["turnover", false], d07: ["turnover", true],
  d08: ["lamington", I.choc, false], d09: ["lamington", I.choc, true],
  d10: ["slice", "#5A3A26", I.caramel, "flake"], d11: ["slice", "#5A3A26", I.caramel, null],
  d12: ["slice", "#7A4A26", I.caramel, "drizzle"], d13: ["slice", "#2E2622", I.caramel, "drizzle"],
  d14: ["slice", "#5A3A26", I.caramel, "coconut"], d15: ["slice", "#D9A648", I.biscuit, null],
  d16: ["slice", I.yellow, I.biscuit, "drizzle"], d17: ["lolly"],
  d18: ["rockyroad"], d19: ["slice", I.white, I.choc, "flake"],
  d20: ["slice", "#2E2622", I.white, "coconut"], d21: ["slice", "#3A2418", "#4A2F1D", null],
  d22: ["cake", I.red, I.white], d23: ["cake", I.white, "#8A5A2E"],
  d24: ["cake", "#C9955A", "#E8D29A"], d25: ["tart", "#F2D98A", null],
  d26: ["tart", I.pink, I.choc], d27: ["yoyo"], d28: ["tart", I.jam, null],
  d29: ["tart", I.yellow, null], d30: ["gingerman"], d31: ["cookie"],
  d32: ["marshstick"], d33: ["log"],
  h01: ["corndog"], h02: ["potatocake"], h03: ["hashbrown"], h04: ["dimsim"],
  h05: ["springroll"], h06: ["wing"], h07: ["sausage", "#D8483A"],
  h08: ["sausage", "#F0C88A"], h09: ["fritter"],
  h10: ["fritter"], h11: ["dimsim"], h12: ["wing"], h13: ["fritter"],
  h14: ["sroll"], h15: ["sandwich", I.red, I.yellow], h16: ["sandwich", I.red, I.yellow],
  h17: ["roll", I.red, I.yellow], h18: ["roll", I.red, I.yellow],
  k01: ["can", "#C8402F"], k02: ["can", "#E8B84A"], k03: ["bottle", "#C8402F"],
  k04: ["bottle", "#7FB2D8"], k05: ["coffee"], k06: ["bottle", "#8A5A34"],
};

export const CAT_FALLBACK = {
  Pies: ["pie", I.meat], Sandwiches: ["sandwich", I.ham, I.green],
  "Rolls & Buns": ["roll", I.green, I.red], Sweets: ["slice", I.caramel, I.biscuit, null],
  "Hot Food": ["potatocake"], Drinks: ["can", "#9C907A"],
};
